apiVersion: apps.api.test/v1alpha1
kind: Simpleapi
metadata:
  labels:
    app.kubernetes.io/name: my-api
    app.kubernetes.io/managed-by: operator
    app: my-api
  name: simpleapi-sample
  namespace: default
spec:
  image: "xxx.azurecr.io/fast-demo:v24"
  version: "v24"
  port: 8000
  replicas: 1
