apiVersion: apps.api.test/v1alpha1
kind: Simpleapi
metadata:
  labels:
    app.kubernetes.io/name: api-operator
    app.kubernetes.io/managed-by: kustomize
  name: simpleapi-sample
  namespace: default
spec:
  image: "reg.azurecr.io/fast-demo:v25"
  version: "v25"
  port: 8000
  replicas: 1
