---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.api.test
  resources:
  - simpleapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.api.test
  resources:
  - simpleapis/finalizers
  verbs:
  - update
- apiGroups:
  - apps.api.test
  resources:
  - simpleapis/status
  verbs:
  - get
  - patch
  - update
