# permissions for end users to edit simpleapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: api-operator
    app.kubernetes.io/managed-by: kustomize
  name: simpleapi-editor-role
rules:
- apiGroups:
  - apps.api.test
  resources:
  - simpleapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.api.test
  resources:
  - simpleapis/status
  verbs:
  - get
